import Link from "next/link";
import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {PageFrame} from "@/app/components/page-frame";

const guides={
 "how-to-build-a-restaurant-brand":{title:"How to build a restaurant brand",intro:"Start with what the restaurant needs to be known for, then carry that idea through every customer touchpoint.",steps:["Clarify the restaurant idea and audience.","Choose a useful position instead of trying to appeal to everyone.","Create the visual identity: logo, colour, typography and graphic language.","Translate the identity into menus, packaging, print and social touchpoints.","Document the rules so future materials stay recognizable."]},
 "choosing-restaurant-colours":{title:"Choosing restaurant colours",intro:"Colour should help customers recognize the restaurant before they read the name.",steps:["Start with the restaurant personality and food experience.","Choose a focused primary palette with supporting colours.","Check contrast and legibility across menus, packaging and digital use.","Test the palette on the actual materials and formats customers will see.","Document the colour system so it stays consistent."]},
 "how-to-choose-the-right-box":{title:"How to choose the right box",intro:"The right box starts with the food and operating reality, not the artwork.",steps:["Consider the food shape, portion and temperature.","Think about steam, grease, stacking and transport.","Choose a format that opens and closes naturally for the customer.","Check storage, packing speed and delivery handling.","Then apply the brand so function and identity work together."]},
 "packaging-for-delivery":{title:"Packaging for delivery",intro:"Delivery packaging has to protect the food while making the brand feel present from handoff to opening.",steps:["Map the delivery journey from kitchen to customer.","Separate hot, cold, wet and fragile items where necessary.","Use seals, bags and secondary packaging to control handling.","Make the opening experience clear and intentional.","Review the system after real deliveries and refine it."]},
 "new-restaurant-branding-checklist":{title:"New restaurant branding checklist",intro:"A new restaurant benefits from making identity decisions before production begins.",steps:["Define the concept, audience and positioning.","Set the naming and visual identity direction.","Prepare core menu and printed collateral.","Plan the packaging system around the menu and service model.","Create launch-ready brand guidelines and social assets."]},
 "opening-a-cafe-bakery-cloud-kitchen":{title:"Opening a café / bakery / cloud kitchen",intro:"Different food businesses need different operating and packaging systems.",steps:["Define the service model and main customer journey.","List the products that actually leave the kitchen.","Choose packaging families that fit the food and volume.","Build the identity across the highest-visibility touchpoints.","Prepare a simple launch checklist for repeatable execution."]},
 "how-to-plan-packaging-quantities":{title:"How to plan packaging quantities",intro:"Quantity planning should follow menu mix, volume and reorder rhythm rather than guesswork.",steps:["Estimate order volume by menu category.","Map each menu item to its packaging components.","Separate high-frequency essentials from occasional formats.","Set an initial quantity and a reorder trigger.","Review actual consumption after launch and adjust."]},
 "how-to-make-packaging-feel-premium":{title:"How to make packaging feel premium",intro:"Premium packaging usually comes from restraint, consistency and a good physical experience.",steps:["Use a clear visual hierarchy instead of adding decoration everywhere.","Keep typography, colour and logo treatment consistent.","Choose materials and finishes that support the brand idea.","Pay attention to opening, carrying and handling details.","Apply the same level of care across small touchpoints."]}
} as const;

type GuideSlug=keyof typeof guides;
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;if(!(slug in guides))return {};return {title:guides[slug as GuideSlug].title,description:guides[slug as GuideSlug].intro};}
export function generateStaticParams(){return Object.keys(guides).map(slug=>({slug}));}
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!(slug in guides))notFound();const guide=guides[slug as GuideSlug];return <PageFrame eyebrow="06 / Guidelines" title={guide.title}><article className="guideArticle section"><div className="guideArticleIntro"><p>{guide.intro}</p></div><div className="guideSteps">{guide.steps.map((step,i)=><div key={step}><span>{String(i+1).padStart(2,"0")}</span><p>{step}</p></div>)}</div><div className="guideArticleCta"><h2>Want help applying this to <i>your restaurant?</i></h2><p>Tell Farefold what you&apos;re building and we can turn the direction into a practical brand and packaging system.</p><div><Link className="primary" href={`/contact?product=${encodeURIComponent(guide.title)}`}>Talk to Farefold <span>→</span></Link><Link className="secondary" href="/guidelines">Back to guidelines</Link></div></div></article></PageFrame>}