import type { MetadataRoute } from "next";
import { siteConfig } from "@/lib/site-config";
import { productFamilies, businessTypes, foodTypes, materials, packagingProblems } from "@/lib/data";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  // Every detail-page slug generated by app/products/[slug],
  // app/businesses/[slug], app/foods/[slug], app/materials/[slug] and
  // app/solutions/[slug] — kept in sync with those routes' own
  // generateStaticParams because all of them read the same taxonomy
  // arrays.
  const taxonomyPaths = [
    ...productFamilies.map((node) => `/products/${node.slug}`),
    ...businessTypes.map((node) => `/businesses/${node.slug}`),
    ...foodTypes.map((node) => `/foods/${node.slug}`),
    ...materials.map((node) => `/materials/${node.slug}`),
    ...packagingProblems.map((node) => `/solutions/${node.slug}`),
  ];

  const topLevelPaths = [
    "/products",
    "/custom-packaging",
    "/solutions",
    "/businesses",
    "/materials",
    "/lab",
    "/foods",
  ];

  return [
    {
      url: siteConfig.url,
      lastModified,
      changeFrequency: "monthly",
      priority: 1,
    },
    ...topLevelPaths.map((path) => ({
      url: `${siteConfig.url}${path}`,
      lastModified,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    })),
    ...taxonomyPaths.map((path) => ({
      url: `${siteConfig.url}${path}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    })),
  ];
}
