import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/taxonomy/Breadcrumbs";
import { TaxonomyCard } from "@/components/taxonomy/TaxonomyCard";
import { ProductFormatCatalogue } from "@/components/taxonomy/ProductFormatCatalogue";
import { productFamilies, getNodeBySlug, getChildren, getAncestors, getRelated } from "@/lib/data";
type Params={slug:string}; type Props={params:Promise<Params>}; export const dynamicParams=false;
export function generateStaticParams():Params[]{return productFamilies.map(f=>({slug:f.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const node=getNodeBySlug(productFamilies,slug);if(!node)return{};return{title:node.name,description:node.description??`${node.name} — Farefold packaging family.`,alternates:{canonical:`/products/${node.slug}`}};}
export default async function ProductFamilyPage({params}:Props){const {slug}=await params;const node=getNodeBySlug(productFamilies,slug);if(!node)notFound();const children=getChildren(productFamilies,node.slug);const ancestors=getAncestors(productFamilies,node.slug);const related=getRelated("productFamily",node.slug);return <div className="bg-[#f3efe6] text-[#171614]"><div className="mx-auto w-full max-w-[120rem] px-5 py-16 sm:px-8 sm:py-24 lg:px-14"><Breadcrumbs items={[{name:"Products",href:"/products"},...ancestors.map(a=>({name:a.name,href:`/products/${a.slug}`})),{name:node.name}]}/><div className="mt-10 border-b border-black/15 pb-10"><p className="text-xs uppercase tracking-[0.24em] text-[#567000]">Packaging family</p><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[0.92] tracking-[-0.05em] sm:text-7xl">{node.name}</h1>{node.description&&<p className="mt-6 max-w-3xl text-lg leading-8 text-black/60">{node.description}</p>}</div>{children.length>0?<ul className="mt-10 grid gap-px border border-black/15 bg-black/15 sm:grid-cols-2 lg:grid-cols-3">{children.map(child=><TaxonomyCard key={child.slug} href={`/products/${child.slug}`} name={child.name} description={child.description}/>)}</ul>:<ProductFormatCatalogue slug={node.slug} categoryName={node.name}/>}<div className="mt-14 grid gap-4 border-t border-black/15 pt-8 sm:grid-cols-3"><Link href="/businesses" className="border border-black/15 p-5 hover:bg-white/60"><span className="text-xs uppercase tracking-[0.2em] text-black/40">Business</span><strong className="mt-3 block text-xl">Shop by restaurant type</strong><span className="mt-2 block text-sm text-black/60">See the packaging problems different food businesses face.</span></Link><Link href="/branding" className="border border-black/15 p-5 hover:bg-white/60"><span className="text-xs uppercase tracking-[0.2em] text-black/40">Branding</span><strong className="mt-3 block text-xl">Build the brand</strong><span className="mt-2 block text-sm text-black/60">Carry the identity from the logo into every physical touchpoint.</span></Link><Link href="/contact" className="border border-black/15 p-5 hover:bg-white/60"><span className="text-xs uppercase tracking-[0.2em] text-black/40">Custom</span><strong className="mt-3 block text-xl">Need another format?</strong><span className="mt-2 block text-sm text-black/60">Start with the food and the problem; we will shape the packaging around it.</span></Link></div>{related.length>0&&null}</div></div>;}